quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.skills.directories=.skills/skills
#quarkus.langchain4j.openai.base-url=http://yourserver

